### PR TITLE
Remove duplicate yireo/magento2-replace-graphql replaces

### LINKED ISSUE #2: Error on 2.3.2
On a clean install of Magento 2.3.2 i get a error on;

`composer require yireo/magento2-replace-all:2.3.2`

Your requirements could not be resolved to an installable set of packages

running `composer require yireo/magento2-replace-all:2.3.1` on the same clean install works but ...

running setup:upgrade after that give's us this nice error;

`Class Magento\InventoryReservationsApi\Model\AppendReservationsInterface does not exist

In ClassReader.php line 35:`

### PR DESCRIPTION
**Pull request by nocturnalfrog**
Fixes https://github.com/yireo/magento2-replace-all/issues/2

- The  "magento/module-send-friend-graph-ql" and "magento/module-swatches-graph-ql" replaces are GraphQL related and don't belong to the yireo/magento2-replace-core repository.
- The new composer version restraint allows for bugfixes like these to be easily rolled out.

### CODE REVIEW

**Comment by jissereitsma** [comment]
I love the version constraint, much better.

However, you can't simply exclude GraphQL. When the SendFriend module is removed, but it's GraphQL equivalent is still there, the SendFriend GraphQL module still depends on the SendFriend module and this breaks the `bin/magento setup:di:compile` command. So if this repo is used to remove the SendFriend module, there is little use for the GraphQL equivalent. Did you bump into specific issues here?

**Comment by nocturnalfrog** [comment]
Ah, I was afraid that those 2 GraphQL modules were in here for a reason...

But the thing is; as long as these replaces are in the `yireo/magento2-replace-core` package I can't also add the `yireo/magento2-replace-graphql` package to my Magento composer config because of a "Your requirements could not be resolved to an installable set of packages."

So it appears we're in some kind of deadlock situation:
When `yireo/magento2-replace-core` is installed in isolation we can't really remove the 2 GraphQL modules in this package without breaking Magento.
But we can't have them in here when we also want to include the `yireo/magento2-replace-graphql` in our project.

This probably means that, even though I like the idea of splitting these replaces into different logical groups, composer is not able to handle this.  

I guess that, to "fix" this, you could create separate packages for all possible combinations, but that just seems like a terrible drag.

**Comment by norgeindian** [comment]
@jissereitsma , did you find a good solution for this issue?
We really love your approach as we always thought about a good solution to somehow remove unused modules, so thanks for spending time on that.
But as we definitely need the MSI, the replace-all package is not working for us.
So it would really be great if we could include all the other packages like they are, which is currently not possible unfortunately.
Is there maybe a way to somehow teach composer to ignore duplicate replacements?

**Comment by jissereitsma** [comment]
@norgeindian Unfortunately there is no good solution here. The `replace` doesn't allow for duplicate replacements. You can't either undo replacements. The only logical idea I can come up with so far is to build a script that allows you to pick which set of replacements you need, merge things together and then generate a composer file correspondingly. Lots of hard work needed there. And I'm not sure if it is a handy solution. As of yet, manual checking still seems to be the best approach :(

**Pull request closed without merging**
